services:
  tolls-db:
    image: postgres:alpine
    restart: always
    container_name: tolls-db
    environment:
      POSTGRES_DB: tolls
      POSTGRES_USER: softeng
      POSTGRES_PASSWORD: softeng2024
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    